# Site settings
title: 李承阳的博客
SEOTitle: Li Chengyang Blog
header-img: img/home-bg-o.jpg
email: lcylmhlcy@163.com
description: "这里是李承阳的个人博客，与你一起发现更大的世界。"
keyword: "lichengyang"
url: "https://lcylmhlcy.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: True
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    lcylmhlcy
#twitter_username:   huxpro
#facebook_username:  huxpro
linkedin_username:  承阳-李-4717b8165



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: Li Chengyang

# Netease setttings
netease_comment: false



# Analytics settings
#Baidu Analytics 
#ba_track_id: 71221e00ad529da9583bbbe691f3c1fa

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "计算机技术 专业硕士<br>信息科学与工程学院<br>中国石油大学（北京）<br>昌平，北京，中国"
sidebar-avatar: /img/mypic3.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
    #{
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
    #    title: "乱序",
    #    href: "http://mida.re/"
    #},{
    #    title: "前端外刊评论",
    #    href: "http://qianduan.guru/"
    #},{
    #    title: "天镶的博客",
    #    href: "http://lingyu.wang/"
    #},{
    #    title: "Luke 的自留地",
    #    href: "http://hmqk1995.github.io"
    #},{
    #    title: "Ebn's Blog",
    #    href: "http://ebnbin.com/"
    #},{
    #    title: "SmdCn's Blog",
    #    href: "http://blog.smdcn.net"
    #},{
    #    title: "解旻的博客",
    #    href: "http://xieminis.me/"
    #},{
    #    title: "DHong Say",
    #    href: "http://dhong.co"
    #},{
    #    title: "尹峰以为",
    #    href: "http://ingf.github.io/"
    #},{
    #    title: "前端神盾局",
    #    href: "http://wepiaofei.github.io/blog/"
    #}
#]
